
version: '2'

services:
  fires-data-task:
    image: 'terrabrasilis/fires-data-task-main:v1.4.0'
    container_name: fires-data-task
    restart: always
    volumes:
      - '/data/fires/raster:/usr/local/data'
    environment:
        PG_DETER_HOST: 192.168.1.17
        PG_DETER_PORT: 5432
        PG_FIRES_HOST: 192.168.1.18
        PG_FIRES_PORT: 5432
        DETER_VIEW_DATE: '2023-08-01'
    networks:
      - proxy_default

networks:
  proxy_default:
    external: true