
version: '2'

services:
  fires-data-task:
    image: 'terrabrasilis/fires-data-task-all-biomes:v1.5.1'
    container_name: fires-data-task
    restart: always
    volumes:
      - './data:/usr/local/data'
    environment:
        DETER_VIEW_DATE: '2023-08-01'
    networks:
      - proxy_default

networks:
  proxy_default: